export const BR_STATES = [
  { uf: 'AC', name: 'Acre' }, { uf: 'AL', name: 'Alagoas' }, { uf: 'AP', name: 'Amapá' },
  { uf: 'AM', name: 'Amazonas' }, { uf: 'BA', name: 'Bahia' }, { uf: 'CE', name: 'Ceará' },
  { uf: 'DF', name: 'Distrito Federal' }, { uf: 'ES', name: 'Espírito Santo' }, { uf: 'GO', name: 'Goiás' },
  { uf: 'MA', name: 'Maranhão' }, { uf: 'MT', name: 'Mato Grosso' }, { uf: 'MS', name: 'Mato Grosso do Sul' },
  { uf: 'MG', name: 'Minas Gerais' }, { uf: 'PA', name: 'Pará' }, { uf: 'PB', name: 'Paraíba' },
  { uf: 'PR', name: 'Paraná' }, { uf: 'PE', name: 'Pernambuco' }, { uf: 'PI', name: 'Piauí' },
  { uf: 'RJ', name: 'Rio de Janeiro' }, { uf: 'RN', name: 'Rio Grande do Norte' }, { uf: 'RS', name: 'Rio Grande do Sul' },
  { uf: 'RO', name: 'Rondônia' }, { uf: 'RR', name: 'Roraima' }, { uf: 'SC', name: 'Santa Catarina' },
  { uf: 'SP', name: 'São Paulo' }, { uf: 'SE', name: 'Sergipe' }, { uf: 'TO', name: 'Tocantins' }
];

export const STATE_DDD = {
  AC: '68', AL: '82', AP: '96', AM: '92', BA: '71', CE: '85', DF: '61', ES: '27', GO: '62',
  MA: '98', MT: '65', MS: '67', MG: '31', PA: '91', PB: '83', PR: '41', PE: '81', PI: '86',
  RJ: '21', RN: '84', RS: '51', RO: '69', RR: '95', SC: '48', SP: '11', SE: '79', TO: '63'
};

export const REAL_COMPANIES_DATABASE = [
  {
    id: 'real_mid_1',
    company: 'Tito Tech',
    cnpj: '42.980.112/0001-34',
    name: 'Diego Tito',
    title: 'YouTuber & Criador de Conteúdo de Hardware',
    domain: 'youtube.com/@titotech',
    size: 'Microempresa (1-5 func)',
    country: 'SP - São Paulo',
    tech: ['OBS Studio', 'YouTube AdSense', 'Amazon Associates', 'Instagram Ads'],
    linkedin: 'linkedin.com/in/diegotito',
    email: 'contato@titotech.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 180.000 / ano',
    phone: '+55 11 99823-4554',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '25%',
    sector: 'CRIADORES_MID',
    foundationYear: 2021,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/titotech',
    description: 'Canal de tecnologia focado em reviews de hardware, montagem de PCs gamer e guias de custo-benefício de peças importadas.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_mid_2',
    company: 'Gabriela Jojo (Caju em Cena)',
    cnpj: '45.101.883/0001-02',
    name: 'Gabriela Joyce',
    title: 'Streamer / Influenciadora de Gaming',
    domain: 'twitch.tv/caju_em_cena',
    size: 'Microempresa (1-3 func)',
    country: 'PR - Curitiba',
    tech: ['Streamlabs', 'Twitch Partner Subscriptions', 'Discord Community Builder'],
    linkedin: 'linkedin.com/company/cajuemcena',
    email: 'comercial@cajuemcena.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 72.000 / ano',
    phone: '+55 41 99612-4411',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '15%',
    sector: 'CRIADORES_MID',
    foundationYear: 2022,
    taxEstimate: 'Microempreendedor Individual (MEI)',
    instagram: 'https://instagram.com/caju_em_cena',
    description: 'Streamer em ascensão focada em transmissões de Valorant, campeonatos amadores e engajamento via canais de Discord e TikTok.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_mid_3',
    company: 'Guto TV',
    cnpj: '38.544.120/0001-88',
    name: 'Gustavo de Lima',
    title: 'Criador de Conteúdo / Humorista',
    domain: 'youtube.com/@gutotv',
    size: 'Microempresa (1-4 func)',
    country: 'RJ - Rio de Janeiro',
    tech: ['Adobe Premiere', 'YouTube Analytics', 'Vmix Studio'],
    linkedin: 'linkedin.com/in/gustavogutotv',
    email: 'comercial@gutotv.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 140.000 / ano',
    phone: '+55 21 99122-8877',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '10%',
    sector: 'CRIADORES_MID',
    foundationYear: 2019,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/gutotv',
    description: 'Humorista independente focado em dublagens paródicas de bichos e reels de humor cotidiano com alta viralidade orgânica.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_fisio_1',
    company: 'Clínica Fisio & Pilates Presidente Prudente',
    cnpj: '28.110.941/0001-50',
    name: 'Dra. Aline Mendes',
    title: 'Fisioterapeuta / Sócia',
    domain: 'clinicafisioprudente.com.br',
    size: 'Microempresa (1-9 func)',
    country: 'SP - Presidente Prudente',
    tech: ['Instagram Ads', 'WhatsApp Business', 'Doctoralia Scheduling'],
    linkedin: 'linkedin.com/company/fisio-pilates-prudente',
    email: 'contato@clinicafisioprudente.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 310.000 / ano',
    phone: '+55 18 99790-5222',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '18%',
    sector: 'FISIO',
    foundationYear: 2017,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/fisio.prudente',
    description: 'Clínica especializada em reabilitação ortopédica, RPG, pilates clínico e atendimento pós-cirúrgico de atletas locais.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_psi_1',
    company: 'Humanamente - Clínica Integrada de Psicologia',
    cnpj: '35.402.663/0001-11',
    name: 'Dr. Lucas Ribeiro',
    title: 'Psicólogo Clínico / Diretor',
    domain: 'humanamentepsicologia.com.br',
    size: 'Microempresa (1-6 func)',
    country: 'SP - Presidente Prudente',
    tech: ['WhatsApp Business', 'Google Maps Local', 'Instagram Ads'],
    linkedin: 'linkedin.com/company/humanamente-prudente',
    email: 'atendimento@humanamentepsicologia.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 220.000 / ano',
    phone: '+55 18 99639-4405',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '12%',
    sector: 'PSICOLOGIA',
    foundationYear: 2020,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/psicologia.humanamente',
    description: 'Consultório de saúde mental focado em Terapia Cognitivo-Comportamental (TCC), atendimento infantil e avaliação neuropsicológica.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_personal_1',
    company: 'Bruno Personal & Team Fitness',
    cnpj: '46.120.301/0001-90',
    name: 'Bruno Rodrigues',
    title: 'Personal Trainer / Consultor Executivo',
    domain: 'brunorodriguespersonal.com.br',
    size: 'Microempresa (1-3 func)',
    country: 'SP - Presidente Prudente',
    tech: ['WhatsApp Business', 'Instagram Ads', 'MFit Personal App'],
    linkedin: 'linkedin.com/in/brunoprofpersonal',
    email: 'contato@brunorodriguespersonal.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 96.000 / ano',
    phone: '+55 18 99792-1234',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '30%',
    sector: 'PERSONAL',
    foundationYear: 2021,
    taxEstimate: 'Microempreendedor Individual (MEI)',
    instagram: 'https://instagram.com/bruno_personal_fit',
    description: 'Consultoria de emagrecimento, reabilitação física, musculação adaptada e acompanhamento nutricional com app de treinos exclusivo.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_acad_1',
    company: 'Iron Prudentina Fitness',
    cnpj: '31.112.556/0001-44',
    name: 'Marcos Iron',
    title: 'Sócio-Fundador',
    domain: 'ironprudentina.com.br',
    size: 'Média (10-30 func)',
    country: 'SP - Presidente Prudente',
    tech: ['Pacto Sistema de Gestão', 'Instagram Ads', 'Facebook Business Suite'],
    linkedin: 'linkedin.com/company/ironprudentina',
    email: 'gerencia@ironprudentina.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 780.000 / ano',
    phone: '+55 18 99639-5500',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '20%',
    sector: 'ACADEMIA',
    foundationYear: 2018,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/ironprudentina',
    description: 'Academia de musculação raiz de grande porte, com estrutura de fisiculturismo, treinamento funcional e cross training no centro da cidade.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_4',
    company: 'Casimiro Miguel (CazéTV)',
    cnpj: '45.890.312/0001-09',
    name: 'Casimiro Miguel',
    title: 'Criador de Conteúdo / CEO',
    domain: 'youtube.com/@cazetv',
    size: 'Grande (50-200 func)',
    country: 'RJ - Rio de Janeiro',
    tech: ['YouTube Live', 'Twitch Studio', 'vMix Enterprise', 'Adobe Premiere'],
    linkedin: 'linkedin.com/company/cazetv',
    email: 'comercial@cazetv.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 24.000.000 / ano',
    phone: '+55 21 99882-1020',
    hiredSdr: true,
    funding: 'Parceria LiveMode',
    growth: '110%',
    sector: 'CRIADORES',
    foundationYear: 2021,
    taxEstimate: 'Regime Lucro Presumido',
    instagram: 'https://instagram.com/casimiro',
    description: 'Um dos maiores ecossistemas esportivos e de reacts do mundo, com transmissões oficiais e patrocínios de marcas globais.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_5',
    company: 'Victor Augusto (LOUD Coringa)',
    cnpj: '39.421.564/0001-81',
    name: 'Victor Augusto',
    title: 'Streamer / Influenciador',
    domain: 'twitch.tv/loud_coringa',
    size: 'Média (10-30 func)',
    country: 'SP - São Paulo',
    tech: ['Twitch API', 'Instagram Creator Tools', 'Discord Community Builder'],
    linkedin: 'linkedin.com/company/loud',
    email: 'coringa@loud.gg',
    emailStatus: 'verified',
    revenue: 'R$ 8.500.000 / ano',
    phone: '+55 11 99554-4321',
    hiredSdr: true,
    funding: 'Grupo LOUD',
    growth: '45%',
    sector: 'CRIADORES',
    foundationYear: 2019,
    taxEstimate: 'Regime Lucro Presumido',
    instagram: 'https://instagram.com/loud_coringa',
    description: 'Maior streamer individual da Twitch no Brasil, focado em entretenimento, transmissões ao vivo de GTA RP e campanhas publicitárias de grande escala.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  }
];

export const initialPackages = [];
