export const BR_STATES = [
  { uf: 'AC', name: 'Acre' }, { uf: 'AL', name: 'Alagoas' }, { uf: 'AP', name: 'Amapá' },
  { uf: 'AM', name: 'Amazonas' }, { uf: 'BA', name: 'Bahia' }, { uf: 'CE', name: 'Ceará' },
  { uf: 'DF', name: 'Distrito Federal' }, { uf: 'ES', name: 'Espírito Santo' }, { uf: 'GO', name: 'Goiás' },
  { uf: 'MA', name: 'Maranhão' }, { uf: 'MT', name: 'Mato Grosso' }, { uf: 'MS', name: 'Mato Grosso do Sul' },
  { uf: 'MG', name: 'Minas Gerais' }, { uf: 'PA', name: 'Pará' }, { uf: 'PB', name: 'Paraíba' },
  { uf: 'PR', name: 'Paraná' }, { uf: 'PE', name: 'Pernambuco' }, { uf: 'PI', name: 'Piauí' },
  { uf: 'RJ', name: 'Rio de Janeiro' }, { uf: 'RN', name: 'Rio Grande do Norte' }, { uf: 'RS', name: 'Rio Grande do Sul' },
  { uf: 'RO', name: 'Rondônia' }, { uf: 'RR', name: 'Roraima' }, { uf: 'SC', name: 'Santa Catarina' },
  { uf: 'SP', name: 'São Paulo' }, { uf: 'SE', name: 'Sergipe' }, { uf: 'TO', name: 'Tocantins' }
];

export const STATE_DDD = {
  AC: '68', AL: '82', AP: '96', AM: '92', BA: '71', CE: '85', DF: '61', ES: '27', GO: '62',
  MA: '98', MT: '65', MS: '67', MG: '31', PA: '91', PB: '83', PR: '41', PE: '81', PI: '86',
  RJ: '21', RN: '84', RS: '51', RO: '69', RR: '95', SC: '48', SP: '11', SE: '79', TO: '63'
};

export const REAL_COMPANIES_DATABASE = [
  {
    id: 'real_mid_1',
    company: 'Tito Tech',
    cnpj: '42.980.112/0001-34',
    name: 'Diego Tito',
    title: 'YouTuber & Criador de Conteúdo de Hardware',
    domain: 'youtube.com/@titotech',
    size: 'Microempresa (1-5 func)',
    country: 'SP - São Paulo',
    tech: ['OBS Studio', 'YouTube AdSense', 'Amazon Associates', 'Instagram Ads'],
    linkedin: 'linkedin.com/in/diegotito',
    email: 'contato@titotech.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 180.000 / ano',
    phone: '+55 11 99823-4554',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '25%',
    sector: 'CRIADORES_MID',
    foundationYear: 2021,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/titotech',
    description: 'Canal de tecnologia focado em reviews de hardware, montagem de PCs gamer e guias de custo-benefício de peças importadas.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_mid_2',
    company: 'Gabriela Jojo (Caju em Cena)',
    cnpj: '45.101.883/0001-02',
    name: 'Gabriela Joyce',
    title: 'Streamer / Influenciadora de Gaming',
    domain: 'twitch.tv/caju_em_cena',
    size: 'Microempresa (1-3 func)',
    country: 'PR - Curitiba',
    tech: ['Streamlabs', 'Twitch Partner Subscriptions', 'Discord Community Builder'],
    linkedin: 'linkedin.com/company/cajuemcena',
    email: 'comercial@cajuemcena.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 72.000 / ano',
    phone: '+55 41 99612-4411',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '15%',
    sector: 'CRIADORES_MID',
    foundationYear: 2022,
    taxEstimate: 'Microempreendedor Individual (MEI)',
    instagram: 'https://instagram.com/caju_em_cena',
    description: 'Streamer em ascensão focada em transmissões de Valorant, campeonatos amadores e engajamento via canais de Discord e TikTok.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_mid_3',
    company: 'Guto TV',
    cnpj: '38.544.120/0001-88',
    name: 'Gustavo de Lima',
    title: 'Criador de Conteúdo / Humorista',
    domain: 'youtube.com/@gutotv',
    size: 'Microempresa (1-4 func)',
    country: 'RJ - Rio de Janeiro',
    tech: ['Adobe Premiere', 'YouTube Analytics', 'Vmix Studio'],
    linkedin: 'linkedin.com/in/gustavogutotv',
    email: 'comercial@gutotv.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 140.000 / ano',
    phone: '+55 21 99122-8877',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '10%',
    sector: 'CRIADORES_MID',
    foundationYear: 2019,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/gutotv',
    description: 'Humorista independente focado em dublagens paródicas de bichos e reels de humor cotidiano com alta viralidade orgânica.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_fisio_1',
    company: 'Clínica Fisio & Pilates Presidente Prudente',
    cnpj: '28.110.941/0001-50',
    name: 'Dra. Aline Mendes',
    title: 'Fisioterapeuta / Sócia',
    domain: 'clinicafisioprudente.com.br',
    size: 'Microempresa (1-9 func)',
    country: 'SP - Presidente Prudente',
    tech: ['Instagram Ads', 'WhatsApp Business', 'Doctoralia Scheduling'],
    linkedin: 'linkedin.com/company/fisio-pilates-prudente',
    email: 'contato@clinicafisioprudente.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 310.000 / ano',
    phone: '+55 18 99790-5222',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '18%',
    sector: 'FISIO',
    foundationYear: 2017,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/fisio.prudente',
    description: 'Clínica especializada em reabilitação ortopédica, RPG, pilates clínico e atendimento pós-cirúrgico de atletas locais.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_psi_1',
    company: 'Humanamente - Clínica Integrada de Psicologia',
    cnpj: '35.402.663/0001-11',
    name: 'Dr. Lucas Ribeiro',
    title: 'Psicólogo Clínico / Diretor',
    domain: 'humanamentepsicologia.com.br',
    size: 'Microempresa (1-6 func)',
    country: 'SP - Presidente Prudente',
    tech: ['WhatsApp Business', 'Google Maps Local', 'Instagram Ads'],
    linkedin: 'linkedin.com/company/humanamente-prudente',
    email: 'atendimento@humanamentepsicologia.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 220.000 / ano',
    phone: '+55 18 99639-4405',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '12%',
    sector: 'PSICOLOGIA',
    foundationYear: 2020,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/psicologia.humanamente',
    description: 'Consultório de saúde mental focado em Terapia Cognitivo-Comportamental (TCC), atendimento infantil e avaliação neuropsicológica.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_personal_1',
    company: 'Bruno Personal & Team Fitness',
    cnpj: '46.120.301/0001-90',
    name: 'Bruno Rodrigues',
    title: 'Personal Trainer / Consultor Executivo',
    domain: 'brunorodriguespersonal.com.br',
    size: 'Microempresa (1-3 func)',
    country: 'SP - Presidente Prudente',
    tech: ['WhatsApp Business', 'Instagram Ads', 'MFit Personal App'],
    linkedin: 'linkedin.com/in/brunoprofpersonal',
    email: 'contato@brunorodriguespersonal.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 96.000 / ano',
    phone: '+55 18 99792-1234',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '30%',
    sector: 'PERSONAL',
    foundationYear: 2021,
    taxEstimate: 'Microempreendedor Individual (MEI)',
    instagram: 'https://instagram.com/bruno_personal_fit',
    description: 'Consultoria de emagrecimento, reabilitação física, musculação adaptada e acompanhamento nutricional com app de treinos exclusivo.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_acad_1',
    company: 'Iron Prudentina Fitness',
    cnpj: '31.112.556/0001-44',
    name: 'Marcos Iron',
    title: 'Sócio-Fundador',
    domain: 'ironprudentina.com.br',
    size: 'Média (10-30 func)',
    country: 'SP - Presidente Prudente',
    tech: ['Pacto Sistema de Gestão', 'Instagram Ads', 'Facebook Business Suite'],
    linkedin: 'linkedin.com/company/ironprudentina',
    email: 'gerencia@ironprudentina.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 780.000 / ano',
    phone: '+55 18 99639-5500',
    hiredSdr: false,
    funding: 'Capital Próprio',
    growth: '20%',
    sector: 'ACADEMIA',
    foundationYear: 2018,
    taxEstimate: 'Regime Simples Nacional',
    instagram: 'https://instagram.com/ironprudentina',
    description: 'Academia de musculação raiz de grande porte, com estrutura de fisiculturismo, treinamento funcional e cross training no centro da cidade.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_4',
    company: 'Casimiro Miguel (CazéTV)',
    cnpj: '45.890.312/0001-09',
    name: 'Casimiro Miguel',
    title: 'Criador de Conteúdo / CEO',
    domain: 'youtube.com/@cazetv',
    size: 'Grande (50-200 func)',
    country: 'RJ - Rio de Janeiro',
    tech: ['YouTube Live', 'Twitch Studio', 'vMix Enterprise', 'Adobe Premiere'],
    linkedin: 'linkedin.com/company/cazetv',
    email: 'comercial@cazetv.com.br',
    emailStatus: 'verified',
    revenue: 'R$ 24.000.000 / ano',
    phone: '+55 21 99882-1020',
    hiredSdr: true,
    funding: 'Parceria LiveMode',
    growth: '110%',
    sector: 'CRIADORES',
    foundationYear: 2021,
    taxEstimate: 'Regime Lucro Presumido',
    instagram: 'https://instagram.com/casimiro',
    description: 'Um dos maiores ecossistemas esportivos e de reacts do mundo, com transmissões oficiais e patrocínios de marcas globais.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  },
  {
    id: 'real_5',
    company: 'Victor Augusto (LOUD Coringa)',
    cnpj: '39.421.564/0001-81',
    name: 'Victor Augusto',
    title: 'Streamer / Influenciador',
    domain: 'twitch.tv/loud_coringa',
    size: 'Média (10-30 func)',
    country: 'SP - São Paulo',
    tech: ['Twitch API', 'Instagram Creator Tools', 'Discord Community Builder'],
    linkedin: 'linkedin.com/company/loud',
    email: 'coringa@loud.gg',
    emailStatus: 'verified',
    revenue: 'R$ 8.500.000 / ano',
    phone: '+55 11 99554-4321',
    hiredSdr: true,
    funding: 'Grupo LOUD',
    growth: '45%',
    sector: 'CRIADORES',
    foundationYear: 2019,
    taxEstimate: 'Regime Lucro Presumido',
    instagram: 'https://instagram.com/loud_coringa',
    description: 'Maior streamer individual da Twitch no Brasil, focado em entretenimento, transmissões ao vivo de GTA RP e campanhas publicitárias de grande escala.',
    prospector: 'Sistema',
    approachedBy: null,
    status: 'Novo'
  }
];

export const initialPackages = [];

export const contingencyNichesTemplates = {
  acaiterias: [
    { company: 'Top Açaí', cnpj: '25.109.841/0001-90', name: 'Roberto de Barros', title: 'Proprietário', tech: ['Instagram Ads', 'iFood'], rev: 'R$ 380.000 / ano', tax: 'Simples Nacional', desc: 'Açaiteria artesanal de grande movimento local com foco em entregas rápidas.', insta: 'https://instagram.com/topacaiprudente' },
    { company: 'Gets Açaí', cnpj: '34.201.883/0001-12', name: 'Juliana Gets', title: 'Gerente Geral', tech: ['Instagram Ads', 'WhatsApp Cloud API'], rev: 'R$ 520.000 / ano', tax: 'Simples Nacional', desc: 'Especializada em açaí no copo com acompanhamentos gourmet.', insta: 'https://instagram.com/getsacai' },
    { company: 'Açaí Concept Center', cnpj: '29.302.112/0001-80', name: 'Marcos Concept', title: 'Diretor de Operações', tech: ['iFood', 'Google Maps Local'], rev: 'R$ 680.000 / ano', tax: 'Simples Nacional', desc: 'Franquia de açaí com autoatendimento e ampla variedade de cremes.', insta: 'https://instagram.com/acaiconcept' },
    { company: 'Estação do Açaí Gourmet', cnpj: '41.980.502/0001-33', name: 'Luana Silva', title: 'Sócia', tech: ['Instagram Ads', 'WhatsApp Business'], rev: 'R$ 290.000 / ano', tax: 'MEI', desc: 'Açaiteria focada em barcas de açaí e taças decoradas com chocolates nobres.', insta: 'https://instagram.com/estacao_acai' },
    { company: 'Ponto do Açaí Express', cnpj: '30.120.301/0001-90', name: 'Bruno Mendes', title: 'Gerente de Loja', tech: ['iFood', 'Mercado Pago'], rev: 'R$ 410.000 / ano', tax: 'Simples Nacional', desc: 'Quiosque express localizado em centro comercial movimentado.', insta: 'https://instagram.com/ponto_acai' }
  ],
  criadores: [
    { company: 'Victor Augusto (LOUD Coringa)', cnpj: '39.421.564/0001-81', name: 'Victor Augusto', title: 'Streamer / Influenciador', tech: ['Twitch API', 'OBS Studio'], rev: 'R$ 8.500.000 / ano', tax: 'Lucro Presumido', desc: 'Um dos maiores streamers de GTA RP e entretenimento digital da Twitch.', insta: 'https://instagram.com/loud_coringa' },
    { company: 'Casimiro Miguel (CazéTV)', cnpj: '45.890.312/0001-09', name: 'Casimiro Miguel', title: 'CEO & Criador', tech: ['YouTube Live', 'vMix'], rev: 'R$ 24.000.000 / ano', tax: 'Lucro Presumido', desc: 'Ecossistema pioneiro em transmissões esportivas e reacts multiplataforma.', insta: 'https://instagram.com/casimiro' },
    { company: 'Felipe Neto', cnpj: '22.109.841/0001-20', name: 'Felipe Neto', title: 'YouTuber & Fundador', tech: ['YouTube Studio', 'Adobe Premiere', 'Facebook Suite'], rev: 'R$ 15.000.000 / ano', tax: 'Lucro Presumido', desc: 'Canal de entretenimento e humor no YouTube com audiência massiva infanto-juvenil.', insta: 'https://instagram.com/felipeneto' },
    { company: 'Gaules (Alexandre Borba)', cnpj: '31.420.901/0001-11', name: 'Alexandre Borba', title: 'Streamer / CEO Tribo', tech: ['Twitch Live', 'Discord API'], rev: 'R$ 9.800.000 / ano', tax: 'Lucro Presumido', desc: 'Líder da "Tribo Gaules", focado em coberturas e transmissões oficiais de eSports.', insta: 'https://instagram.com/gaules' },
    { company: 'Alanzoka (Alan Ferreira)', cnpj: '28.980.112/0001-50', name: 'Alan Ferreira', title: 'Streamer de Variedades', tech: ['OBS Studio', 'Twitch Partner Subscriptions'], rev: 'R$ 6.200.000 / ano', tax: 'Lucro Presumido', desc: 'Streamer veterano focado em gameplays de variedades e lançamentos de grandes jogos.', insta: 'https://instagram.com/alanzoka' }
  ],
  criadores_mid: [
    { company: 'Tito Tech', cnpj: '42.980.112/0001-34', name: 'Diego Tito', title: 'Criador de Hardware', tech: ['OBS Studio', 'Amazon Associates'], rev: 'R$ 180.000 / ano', tax: 'Simples Nacional', desc: 'Canal de tecnologia focado em reviews de hardware gamer e montagens de PC.', insta: 'https://instagram.com/titotech' },
    { company: 'Gabriela Jojo (Caju em Cena)', cnpj: '45.101.883/0001-02', name: 'Gabriela Joyce', title: 'Streamer de Gaming', tech: ['Twitch Sub', 'Discord Builder'], rev: 'R$ 72.000 / ano', tax: 'MEI', desc: 'Streamer em ascensão focada em Valorant e campeonatos amadores.', insta: 'https://instagram.com/caju_em_cena' },
    { company: 'Lucas Tech & Gaming', cnpj: '30.109.840/0001-12', name: 'Lucas Ferreira', title: 'Produtor de Conteúdo', tech: ['YouTube Studio', 'OBS Studio'], rev: 'R$ 120.000 / ano', tax: 'Simples Nacional', desc: 'Canal focado em hardware de entrada e tutoriais de otimização de computadores.', insta: 'https://instagram.com/lucas_tech' },
    { company: 'Cozinha da Ju (Receitas)', cnpj: '29.304.590/0001-90', name: 'Juliana Castro', title: 'Criadora Executiva', tech: ['Instagram Ads', 'YouTube AdSense'], rev: 'R$ 150.000 / ano', tax: 'Simples Nacional', desc: 'Canal de culinária prática focando em receitas para o dia a dia e dicas de confeitaria.', insta: 'https://instagram.com/cozinhadaju' },
    { company: 'Canal Viagem & Mochila', cnpj: '41.120.502/0001-01', name: 'Renato Faria', title: 'Criador Independente', tech: ['OBS Studio', 'Google Adsense'], rev: 'R$ 98.000 / ano', tax: 'MEI', desc: 'Vídeos semanais focados em viagens econômicas, mochilões pelo mundo e reviews de hotéis.', insta: 'https://instagram.com/viagem_mochila' }
  ],
  fisio: [
    { company: 'Clínica Fisio & Pilates', cnpj: '28.110.941/0001-50', name: 'Dra. Aline Mendes', title: 'Fisioterapeuta Sócia', tech: ['Instagram Ads', 'Doctoralia'], rev: 'R$ 310.000 / ano', tax: 'Simples Nacional', desc: 'Clínica especializada em reabilitação traumato-ortopédica e pilates clínico.', insta: 'https://instagram.com/fisio.prudente' },
    { company: 'Instituto de Fisioterapia Mendes', cnpj: '33.901.883/0001-11', name: 'Dr. Roberto Mendes', title: 'Diretor Clínico', tech: ['Instagram Ads', 'Google Maps Local'], rev: 'R$ 290.000 / ano', tax: 'Simples Nacional', desc: 'Reabilitação pós-cirúrgica ortopédica e fisioterapia preventiva.', insta: 'https://instagram.com/institutomendes' },
    { company: 'FisioCorpus Reabilitação', cnpj: '29.402.112/0001-08', name: 'Dra. Vanessa Costa', title: 'Sócia Fundadora', tech: ['WhatsApp Business', 'Google Ads'], rev: 'R$ 420.000 / ano', tax: 'Simples Nacional', desc: 'Clínica especializada em fisioterapia respiratória, pilates e reeducação postural RPG.', insta: 'https://instagram.com/fisiocorpus' },
    { company: 'Studio Fisioterapia & RPG', cnpj: '40.980.502/0001-90', name: 'Dra. Luana Souza', title: 'Fisioterapeuta Autônoma', tech: ['Instagram Ads'], rev: 'R$ 110.000 / ano', tax: 'MEI', desc: 'Atendimento clínico individualizado e sessões focadas em postura e coluna.', insta: 'https://instagram.com/fisioglobal' },
    { company: 'Clínica de Traumatologia e Fisio', cnpj: '31.120.301/0001-44', name: 'Dr. Thiago Ribeiro', title: 'Sócio Fisioterapeuta', tech: ['Instagram Ads', 'Doctoralia'], rev: 'R$ 600.000 / ano', tax: 'Simples Nacional', desc: 'Centro de fisioterapia desportiva com foco em atletas de alta performance.', insta: 'https://instagram.com/traumato_fisio' }
  ],
  psicologia: [
    { company: 'Humanamente Psicologia', cnpj: '35.402.663/0001-11', name: 'Dr. Lucas Ribeiro', title: 'Psicólogo Clínico', tech: ['WhatsApp Business', 'Google Maps'], rev: 'R$ 220.000 / ano', tax: 'Simples Nacional', desc: 'Consultório integrado de psicologia focado em Terapia Cognitivo-Comportamental.', insta: 'https://instagram.com/psicologia.humanamente' },
    { company: 'Clínica Viver Bem Psicologia', cnpj: '30.120.590/0001-80', name: 'Dra. Camila Santos', title: 'Psicóloga Sócia', tech: ['Google Maps Local', 'Instagram Ads'], rev: 'R$ 180.000 / / ano', tax: 'Simples Nacional', desc: 'Clínica integrada focada em psicoterapia familiar e atendimento de casais.', insta: 'https://instagram.com/viverbem_psico' },
    { company: 'Espaço Mente Saudável', cnpj: '41.109.840/0001-09', name: 'Dr. Fernando Silva', title: 'Diretor Clínico', tech: ['Google Ads', 'WhatsApp Business'], rev: 'R$ 350.000 / ano', tax: 'Simples Nacional', desc: 'Consultório multidisciplinar de psiquiatria, psicologia clínica e psicopedagogia.', insta: 'https://instagram.com/mentesaudavel' },
    { company: 'Instituto TCC de Psicologia', cnpj: '38.901.883/0001-20', name: 'Dra. Patrícia Oliveira', title: 'Sócia Fundadora', tech: ['Instagram Ads', 'WhatsApp Business'], rev: 'R$ 240.000 / ano', tax: 'Simples Nacional', desc: 'Especialistas em terapia cognitiva, transtornos de ansiedade e depressão.', insta: 'https://instagram.com/institutotcc' },
    { company: 'Consultório de Psicologia & Análise', cnpj: '29.980.112/0001-30', name: 'Dr. Roberto Souza', title: 'Psicólogo e Analista', tech: ['Instagram Ads'], rev: 'R$ 90.000 / ano', tax: 'MEI', desc: 'Atendimentos de psicanálise individualizados para jovens e adultos.', insta: 'https://instagram.com/psicanalise_souza' }
  ],
  personal: [
    { company: 'Bruno Personal & Fitness Trainer', cnpj: '46.120.301/0001-90', name: 'Bruno Rodrigues', title: 'Personal Trainer', tech: ['MFit App', 'Instagram Ads'], rev: 'R$ 96.000 / ano', tax: 'MEI', desc: 'Consultoria online e treinos presenciais personalizados voltados para performance.', insta: 'https://instagram.com/bruno_personal_fit' },
    { company: 'Amanda Silva Personal Trainer', cnpj: '33.901.883/0001-02', name: 'Amanda Silva', title: 'Personal Trainer & Coach', tech: ['Instagram Ads', 'WhatsApp Business'], rev: 'R$ 120.000 / ano', tax: 'Simples Nacional', desc: 'Consultoria fitness focada em emagrecimento feminino e hipertrofia.', insta: 'https://instagram.com/amanda_personal' },
    { company: 'Rodrigo Personal & Coach', cnpj: '29.302.112/0001-11', name: 'Rodrigo Brandão', title: 'Personal Trainer Sócia', tech: ['Instagram Ads', 'MFit App'], rev: 'R$ 150.000 / ano', tax: 'Simples Nacional', desc: 'Treinos individuais e consultoria online focada em performance e definição muscular.', insta: 'https://instagram.com/rodrigo_personal' },
    { company: 'Juliana Costa Consultoria Online', cnpj: '40.980.502/0001-80', name: 'Juliana Costa', title: 'Consultora de Emagrecimento', tech: ['Instagram Ads', 'Hotmart'], rev: 'R$ 190.000 / ano', tax: 'Simples Nacional', desc: 'Programas de emagrecimento online com guias de treinos e acompanhamento.', insta: 'https://instagram.com/jucosta_fit' },
    { company: 'Thiago Fitness Personal', cnpj: '31.120.301/0001-99', name: 'Thiago Ribeiro', title: 'Personal Trainer Clínico', tech: ['WhatsApp Business'], rev: 'R$ 80.000 / ano', tax: 'MEI', desc: 'Treinamento functional focado em reabilitação física e idosos.', insta: 'https://instagram.com/thiago_personal' }
  ],
  academia: [
    { company: 'Iron Prudentina Fitness', cnpj: '31.112.556/0001-44', name: 'Marcos Iron', title: 'Sócio-Fundador', tech: ['Pacto Gestão', 'Facebook Suite'], rev: 'R$ 780.000 / ano', tax: 'Simples Nacional', desc: 'Academia tradicional de musculação com ampla área de musculação e cross-training.', insta: 'https://instagram.com/ironprudentina' },
    { company: 'CrossFit Prudente', cnpj: '28.110.941/0001-08', name: 'Dra. Aline Mendes', title: 'Sócio Executivo', tech: ['Instagram Ads', 'Crossfit Box Planner'], rev: 'R$ 540.000 / ano', tax: 'Simples Nacional', desc: 'Box oficial de crossfit focado em condicionamento e competições amadoras.', insta: 'https://instagram.com/crossfit_prudente' },
    { company: 'Studio Fit & Dance', cnpj: '35.402.663/0001-90', name: 'Dr. Lucas Ribeiro', title: 'Gerente Geral', tech: ['WhatsApp Business', 'Instagram Ads'], rev: 'R$ 310.000 / ano', tax: 'Simples Nacional', desc: 'Estúdio de dança, ritmos e ginástica localizada com forte presença local.', insta: 'https://instagram.com/fit_dance_studio' },
    { company: 'Academia Corpo em Ação', cnpj: '30.120.590/0001-11', name: 'Camila Santos', title: 'Sócia Diretora', tech: ['Pacto Gestão', 'Google Ads'], rev: 'R$ 620.000 / ano', tax: 'Simples Nacional', desc: 'Academia familiar completa com aulas de natação, spinning e musculação.', insta: 'https://instagram.com/corpo_em_acao' },
    { company: 'Power Gym Centro', cnpj: '41.109.840/0001-80', name: 'Fernando Silva', title: 'Proprietário', tech: ['Instagram Ads', 'WhatsApp Business'], rev: 'R$ 410.000 / ano', tax: 'Simples Nacional', desc: 'Academia express de musculação de baixo custo localizada no centro da cidade.', insta: 'https://instagram.com/powergym_centro' }
  ],
  tecnologia: [
    { company: 'Orion Software & SaaS', cnpj: '35.498.112/0001-40', name: 'Gustavo Santos', title: 'Diretor de Tecnologia', tech: ['AWS Cloud', 'NodeJS', 'React', 'HubSpot'], rev: 'R$ 1.800.000 / ano', tax: 'Lucro Presumido', desc: 'Desenvolvimento de sistemas de gestão ERP em nuvem para logística regional.', insta: 'https://instagram.com/orionsoftware' },
    { company: 'Delta Tech Solutions', cnpj: '29.102.304/0001-50', name: 'Rodrigo Brandão', title: 'CEO & Founder', tech: ['Google Workspace', 'Python', 'Stripe'], rev: 'R$ 950.000 / ano', tax: 'Simples Nacional', desc: 'Integração de APIs de pagamento e desenvolvimento sob demanda para fintechs.', insta: 'https://instagram.com/deltatech' },
    { company: 'Smart Analytics Brasil', cnpj: '41.229.840/0001-11', name: 'Clara Vasconcelos', title: 'Head de Operações', tech: ['Metabase', 'Google Cloud', 'PostgreSQL'], rev: 'R$ 1.200.000 / ano', tax: 'Simples Nacional', desc: 'Consultoria especializada em inteligência de dados, dashboards e analytics.', insta: 'https://instagram.com/smartanalytics' },
    { company: 'Vortex CRM & Vendas', cnpj: '30.981.442/0001-90', name: 'Mariana Azevedo', title: 'VP de Marketing', tech: ['WordPress', 'Mailchimp', 'Salesforce'], rev: 'R$ 2.100.000 / ano', tax: 'Lucro Presumido', desc: 'SaaS de automação de marketing e CRM focado em imobiliárias de médio porte.', insta: 'https://instagram.com/vortexcrm' },
    { company: 'Link Digital Agency', cnpj: '28.441.502/0001-09', name: 'Renato Faria', title: 'Sócio Executivo', tech: ['RD Station', 'Tailwind', 'NextJS'], rev: 'R$ 720.000 / ano', tax: 'Simples Nacional', desc: 'Agência focada no desenvolvimento de landing pages de alta conversão e funis.', insta: 'https://instagram.com/linkagency' }
  ]
};
